# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0001_initial'),
        ('courses', '0003_auto_20170228_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='creator',
        ),
        migrations.AddField(
            model_name='course',
            name='all_users',
            field=models.ManyToManyField(related_name='all_courses', to='login_register.User'),
        ),
    ]
